apiVersion: config.openshift.io/v1
kind: OperatorHub
metadata:
  name: cluster
spec:
  disableAllDefaultSources: true
  sources:
        - name: certified-operators
          disabled: false
        - name: community-operators
          disabled: false
        - name: redhat-marketplace
          disabled: false
        - name: redhat-operators
          disabled: false
